"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { Driver, Prediction, Race } from "@/lib/types";

type Tab = "Dashboard" | "Driver Standings" | "Race Calendar" | "Championship Outlook" | "Race Predictions";
const tabs: Tab[] = ["Dashboard", "Driver Standings", "Race Calendar", "Championship Outlook", "Race Predictions"];

function useF1<T>(url: string) {
  const [data, setData] = useState<T | null>(null); const [error, setError] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async (fresh = false) => { setLoading(true); setError(false); try { const separator = url.includes("?") ? "&" : "?"; const response = await fetch(fresh ? `${url}${separator}refresh=1` : url, { cache: "no-store" }); if (!response.ok) throw new Error(); setData(await response.json()); } catch { setError(true); } finally { setLoading(false); } }, [url]);
  useEffect(() => { void load(); }, [load]); return { data, error, loading, refresh: load };
}
const initials = (name: string) => name.split(" ").map((part) => part[0]).join("").slice(0, 3);
function Loader() { return <div className="loader">Loading race intelligence...</div>; }
function ErrorState() { return <div className="error">Unable to load data. Please try again shortly.</div>; }

export function F1Dashboard() {
  const [tab, setTab] = useState<Tab>("Dashboard");
  const standings = useF1<{ drivers: Driver[]; source: string }>("/api/standings");
  const races = useF1<{ races: Race[]; source: string }>("/api/races");
  const championship = useF1<{ predictions: Prediction[] }>("/api/predictions");
  const upcoming = useMemo(() => races.data?.races.filter((race) => race.status === "upcoming") ?? [], [races.data]);
  const [selectedRound, setSelectedRound] = useState("");
  useEffect(() => { if (!selectedRound && upcoming[0]) setSelectedRound(upcoming[0].round); }, [selectedRound, upcoming]);
  const racePrediction = useF1<{ predictions: Prediction[]; race: Race; model: string }>(`/api/predictions?round=${selectedRound}`);
  const content = tab === "Driver Standings" ? <Standings {...standings} />
    : tab === "Race Calendar" ? <Calendar data={races.data?.races} loading={races.loading} error={races.error} />
    : tab === "Championship Outlook" ? <Predictions data={championship.data?.predictions} loading={championship.loading} error={championship.error} title="Championship winner outlook" description="Season-long form based on current championship points and wins." />
    : tab === "Race Predictions" ? <RacePredictions upcoming={upcoming} selectedRound={selectedRound} setSelectedRound={setSelectedRound} data={racePrediction.data?.predictions} race={racePrediction.data?.race} loading={racePrediction.loading} error={racePrediction.error} />
    : <Dashboard drivers={standings.data?.drivers ?? []} nextRace={upcoming[0]} source={standings.data?.source} />;
  return <main className="shell"><aside className="sidebar"><div className="brand"><span>APEX</span><i>F1</i></div><nav>{tabs.map((item, index) => <button key={item} onClick={() => setTab(item)} className={tab === item ? "active" : ""}><b>{["D", "S", "C", "O", "R"][index]}</b><span>{item}</span></button>)}</nav><div className="season">SEASON <b>2026</b><small>Automatic data refresh: 15 minutes</small></div></aside><section className="canvas"><header><div><p className="eyebrow">FORMULA 1 / RACE INTELLIGENCE</p><h1>{tab}</h1></div><div className="live"><span /> LIVE DATA</div></header>{content}</section></main>;
}

function Dashboard({ drivers, nextRace, source }: { drivers: Driver[]; nextRace?: Race; source?: string }) { const leader = drivers[0]; const max = Math.max(...drivers.map((driver) => driver.points), 1); return <><section className="hero glass"><div><p className="eyebrow">CHAMPIONSHIP PULSE</p><h2>{leader ? `${leader.name} leads the grid` : "Loading championship"}</h2><p>{leader ? `${leader.points} points / ${leader.wins} wins / ${leader.team}` : ""}</p></div><div className="hero-number">{leader?.points ?? "-"}<small>PTS</small></div></section><div className="grid"><section className="glass card"><CardTitle title="Driver momentum" sub="Championship points" /><div className="bars">{drivers.slice(0, 5).map((driver) => <div className="bar" key={driver.code}><label><span>{driver.name}</span><b>{driver.points}</b></label><div><i style={{ width: `${driver.points / max * 100}%` }} /></div></div>)}</div></section><section className="glass card next"><CardTitle title="Next on track" sub="Race calendar" />{nextRace ? <><h3>{nextRace.name}</h3><p>{nextRace.circuit}</p><div className="race-meta"><b>{new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(`${nextRace.date}T12:00:00`))}</b><span>{nextRace.country}</span></div></> : <Loader />}</section></div><p className="source-note">Source: {source === "live" ? "Jolpica F1 live feed" : "bundled demo data - live source temporarily unavailable"}</p></>; }
function CardTitle({ title, sub }: { title: string; sub: string }) { return <div className="card-title"><div><h3>{title}</h3><p>{sub}</p></div><b>+</b></div>; }
function Standings({ data, loading, error, refresh }: { data: { drivers: Driver[]; source: string } | null; loading: boolean; error: boolean; refresh: (fresh?: boolean) => Promise<void> }) { if (loading && !data) return <Loader />; if (error && !data) return <ErrorState />; const drivers = data?.drivers ?? []; return <section className="glass table-card"><div className="table-head"><div><p className="eyebrow">CURRENT CHAMPIONSHIP</p><h2>Driver standings</h2></div><button className="refresh" onClick={() => void refresh(true)} disabled={loading}>{loading ? "Refreshing..." : "Refresh standings"}</button></div><p className="data-note">Use Refresh standings to request the newest available championship data now. The source is also cached for up to 15 minutes.</p><div className="table">{drivers.map((driver) => <div className="row" key={driver.code}><strong>0{driver.position}</strong><div className="avatar">{initials(driver.name)}</div><div className="driver"><b>{driver.name}</b><span>{driver.team} / {driver.nationality}</span></div><div className="stat"><b>{driver.wins}</b><span>WINS</span></div><div className="points"><b>{driver.points}</b><span>PTS</span></div></div>)}</div></section>; }
function Calendar({ data, loading, error }: { data?: Race[]; loading: boolean; error: boolean }) { if (loading) return <Loader />; if (error || !data) return <ErrorState />; return <section className="calendar">{data.map((race) => <article className="glass race" key={race.round}><div className="flag">{race.status === "upcoming" ? "UP NEXT" : "COMPLETE"}</div><p>ROUND {race.round}</p><h2>{race.name}</h2><div className="race-bottom"><span>{new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${race.date}T12:00:00`))}</span><span>{race.circuit}<br />{race.locality}, {race.country}</span></div></article>)}</section>; }
function Predictions({ data, loading, error, title, description }: { data?: Prediction[]; loading: boolean; error: boolean; title: string; description: string }) { if (loading) return <Loader />; if (error || !data) return <ErrorState />; return <section className="glass prediction-card"><div className="table-head"><div><p className="eyebrow">MODEL / CHAMPIONSHIP-FORM-V1</p><h2>{title}</h2></div><span>Experimental</span></div><p className="disclaimer">{description} This is an analytical estimate, not betting advice.</p><PredictionRows data={data} /></section>; }
function RacePredictions({ upcoming, selectedRound, setSelectedRound, data, race, loading, error }: { upcoming: Race[]; selectedRound: string; setSelectedRound: (round: string) => void; data?: Prediction[]; race?: Race; loading: boolean; error: boolean }) { return <section className="glass prediction-card"><div className="table-head"><div><p className="eyebrow">MODEL / RACE-FORM-V1</p><h2>Race-by-race predictions</h2></div><span>Experimental</span></div><label className="race-select">Choose an upcoming race<select value={selectedRound} onChange={(event) => setSelectedRound(event.target.value)}>{upcoming.map((item) => <option key={item.round} value={item.round}>Round {item.round}: {item.name}</option>)}</select></label>{race && <p className="data-note">{race.circuit}, {race.country}. The ranking combines current form with a circuit-specific historical feature placeholder.</p>}{loading ? <Loader /> : error || !data ? <ErrorState /> : <PredictionRows data={data} />}</section>; }
function PredictionRows({ data }: { data: Prediction[] }) { return <>{data.slice(0, 5).map((prediction, index) => <div className="prediction" key={prediction.driver}><strong>0{index + 1}</strong><div><b>{prediction.driver}</b><span>{prediction.team} / {prediction.confidence} confidence</span></div><div className="prob"><i style={{ width: `${prediction.winProbability}%` }} /><b>{prediction.winProbability}%</b></div><em>FORM {prediction.form}</em></div>)}</>; }
