"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { Driver, Prediction, Race } from "@/lib/types";

type Tab = "Dashboard" | "Driver Standings" | "Race Calendar" | "Championship Outlook" | "Race Predictions" | "Race Review";
type PredictionContext = { predictions: Prediction[]; race: Race; modelVersion: string; stage: "early" | "sprint-week" | "race-week"; dataThrough: { season: number; round: number }; liveFormThroughRound: number; risk: { level: "High" | "Medium" | "Low"; reasons: string[] } };
type ReviewContext = { race: Race; completed: boolean; actualWinner: { driver: string; team: string; code: string } | null };
type StoredSnapshot = Pick<PredictionContext, "predictions" | "race" | "modelVersion" | "stage"> & { savedAt: string };

const tabs: Tab[] = ["Dashboard", "Driver Standings", "Race Calendar", "Championship Outlook", "Race Predictions", "Race Review"];
const stageLabel = (stage: PredictionContext["stage"]) => stage === "race-week" ? "Grand Prix qualifying model" : stage === "sprint-week" ? "Sprint-informed model" : "Early-week model";

function useF1<T>(url: string, enabled = true) {
  const [data, setData] = useState<T | null>(null); const [error, setError] = useState(false); const [loading, setLoading] = useState(enabled);
  const load = useCallback(async (fresh = false) => { if (!enabled) return; setLoading(true); setError(false); try { const separator = url.includes("?") ? "&" : "?"; const response = await fetch(fresh ? `${url}${separator}refresh=1` : url, { cache: "no-store" }); if (!response.ok) throw new Error(); setData(await response.json()); } catch { setError(true); } finally { setLoading(false); } }, [url, enabled]);
  useEffect(() => { void load(); }, [load]); return { data, error, loading, refresh: load };
}

const initials = (name: string) => name.split(" ").map((part) => part[0]).join("").slice(0, 3);
const snapshotKey = (round: string) => `apex-f1/prediction/${round}`;
function Loader() { return <div className="loader">Loading race intelligence...</div>; }
function ErrorState() { return <div className="error">Unable to load data. Please try again shortly.</div>; }

export function F1Dashboard() {
  const [tab, setTab] = useState<Tab>("Dashboard");
  const standings = useF1<{ drivers: Driver[]; source: string }>("/api/standings");
  const races = useF1<{ races: Race[]; source: string }>("/api/races");
  const championship = useF1<{ predictions: Prediction[] }>("/api/predictions");
  const upcoming = useMemo(() => races.data?.races.filter((race) => race.status === "upcoming") ?? [], [races.data]);
  const completed = useMemo(() => races.data?.races.filter((race) => race.status === "completed") ?? [], [races.data]);
  const [selectedRound, setSelectedRound] = useState("");
  useEffect(() => { if (!selectedRound && upcoming[0]) setSelectedRound(upcoming[0].round); }, [selectedRound, upcoming]);
  const racePrediction = useF1<PredictionContext>(`/api/predictions?round=${selectedRound}`, Boolean(selectedRound));
  const lastCompleted = completed.at(-1);
  const review = useF1<ReviewContext>(`/api/review?round=${lastCompleted?.round ?? ""}`, Boolean(lastCompleted));
  const season = races.data?.races[0]?.date.slice(0, 4) ?? new Date().getFullYear();
  const live = standings.data?.source === "live" && races.data?.source === "live";
  const content = tab === "Driver Standings" ? <Standings {...standings} />
    : tab === "Race Calendar" ? <Calendar data={races.data?.races} loading={races.loading} error={races.error} />
    : tab === "Championship Outlook" ? <Predictions data={championship.data?.predictions} loading={championship.loading} error={championship.error} title="Championship winner outlook" description="Season-long form based on current championship points and wins." />
    : tab === "Race Predictions" ? <RacePredictions upcoming={upcoming} selectedRound={selectedRound} setSelectedRound={setSelectedRound} context={racePrediction.data} loading={racePrediction.loading} error={racePrediction.error} refresh={racePrediction.refresh} />
    : tab === "Race Review" ? <RaceReview context={review.data} loading={review.loading} error={review.error} refresh={review.refresh} />
    : <Dashboard drivers={standings.data?.drivers ?? []} nextRace={upcoming[0]} source={standings.data?.source} />;
  return <main className="shell"><aside className="sidebar"><div className="brand"><span>APEX</span><i>F1</i></div><nav>{tabs.map((item, index) => <button key={item} onClick={() => setTab(item)} className={tab === item ? "active" : ""}><b>{["D", "S", "C", "O", "R", "V"][index]}</b><span>{item}</span></button>)}</nav><div className="season">SEASON <b>{season}</b><small>Jolpica cache: up to 15 minutes</small></div></aside><section className="canvas"><header><div><p className="eyebrow">FORMULA 1 / RACE INTELLIGENCE</p><h1>{tab}</h1></div><div className={`live ${live ? "" : "fallback"}`}><span /> {live ? "LIVE DATA" : "DEMO DATA"}</div></header>{content}</section></main>;
}

function Dashboard({ drivers, nextRace, source }: { drivers: Driver[]; nextRace?: Race; source?: string }) { const leader = drivers[0]; const max = Math.max(...drivers.map((driver) => driver.points), 1); return <><section className="hero glass"><div><p className="eyebrow">CHAMPIONSHIP PULSE</p><h2>{leader ? `${leader.name} leads the grid` : "Loading championship"}</h2><p>{leader ? `${leader.points} points / ${leader.wins} wins / ${leader.team}` : ""}</p></div><div className="hero-number">{leader?.points ?? "-"}<small>PTS</small></div></section><div className="grid"><section className="glass card"><CardTitle title="Driver momentum" sub="Championship points" /><div className="bars">{drivers.slice(0, 5).map((driver) => <div className="bar" key={driver.code}><label><span>{driver.name}</span><b>{driver.points}</b></label><div><i style={{ width: `${driver.points / max * 100}%` }} /></div></div>)}</div></section><section className="glass card next"><CardTitle title="Next on track" sub="Race calendar" />{nextRace ? <><h3>{nextRace.name}</h3><p>{nextRace.circuit}</p><div className="race-meta"><b>{new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(`${nextRace.date}T12:00:00`))}</b><span>{nextRace.country}</span></div></> : <Loader />}</section></div><p className="source-note">Source: {source === "live" ? "Jolpica F1 live feed" : "bundled demo data - live source temporarily unavailable"}</p></>; }
function CardTitle({ title, sub }: { title: string; sub: string }) { return <div className="card-title"><div><h3>{title}</h3><p>{sub}</p></div><b>+</b></div>; }
function Standings({ data, loading, error, refresh }: { data: { drivers: Driver[]; source: string } | null; loading: boolean; error: boolean; refresh: (fresh?: boolean) => Promise<void> }) { if (loading && !data) return <Loader />; if (error && !data) return <ErrorState />; const drivers = data?.drivers ?? []; return <section className="glass table-card"><div className="table-head"><div><p className="eyebrow">CURRENT CHAMPIONSHIP</p><h2>Driver standings</h2></div><button className="refresh" onClick={() => void refresh(true)} disabled={loading}>{loading ? "Refreshing..." : "Refresh standings"}</button></div><p className="data-note">Refresh standings requests the newest available source data now; normal server cache lasts up to 15 minutes.</p><div className="table">{drivers.map((driver) => <div className="row" key={driver.code}><strong>0{driver.position}</strong><div className="avatar">{initials(driver.name)}</div><div className="driver"><b>{driver.name}</b><span>{driver.team} / {driver.nationality}</span></div><div className="stat"><b>{driver.wins}</b><span>WINS</span></div><div className="points"><b>{driver.points}</b><span>PTS</span></div></div>)}</div></section>; }
function Calendar({ data, loading, error }: { data?: Race[]; loading: boolean; error: boolean }) { if (loading) return <Loader />; if (error || !data) return <ErrorState />; return <section className="calendar">{data.map((race) => <article className="glass race" key={race.round}><div className="flag">{race.status === "upcoming" ? "UP NEXT" : "COMPLETE"}</div><p>ROUND {race.round}</p><h2>{race.name}</h2><div className="race-bottom"><span>{new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${race.date}T12:00:00`))}</span><span>{race.circuit}<br />{race.locality}, {race.country}</span></div></article>)}</section>; }
function Predictions({ data, loading, error, title, description }: { data?: Prediction[]; loading: boolean; error: boolean; title: string; description: string }) { if (loading) return <Loader />; if (error || !data) return <ErrorState />; return <section className="glass prediction-card"><div className="table-head"><div><p className="eyebrow">MODEL / CHAMPIONSHIP-FORM-V1</p><h2>{title}</h2></div><span>Experimental</span></div><p className="disclaimer">{description} This is an analytical estimate, not betting advice.</p><PredictionRows data={data} /></section>; }
function RacePredictions({ upcoming, selectedRound, setSelectedRound, context, loading, error, refresh }: { upcoming: Race[]; selectedRound: string; setSelectedRound: (round: string) => void; context: PredictionContext | null; loading: boolean; error: boolean; refresh: (fresh?: boolean) => Promise<void> }) {
  useEffect(() => { if (context) { const snapshot: StoredSnapshot = { race: context.race, predictions: context.predictions, modelVersion: context.modelVersion, stage: context.stage, savedAt: new Date().toISOString() }; window.localStorage.setItem(snapshotKey(context.race.round), JSON.stringify(snapshot)); } }, [context]);
  const race = context?.race;
  return <section className="glass prediction-card"><div className="table-head"><div><p className="eyebrow">MODEL / {context?.modelVersion ?? "RACE-WINNER-GBT-V3"}</p><h2>Race-by-race predictions</h2></div><button className="refresh" onClick={() => void refresh(true)} disabled={loading}>{loading ? "Refreshing..." : "Refresh weekend data"}</button></div><label className="race-select">Choose an upcoming race<select value={selectedRound} onChange={(event) => setSelectedRound(event.target.value)}>{upcoming.map((item) => <option key={item.round} value={item.round}>Round {item.round}: {item.name}</option>)}</select></label>{race && context && <><p className="data-note">{race.circuit}, {race.country}. {stageLabel(context.stage)} uses live form through round {context.liveFormThroughRound || "—"}; it stores this browser’s forecast for the post-race review.</p><RiskCard risk={context.risk} /></>}{loading ? <Loader /> : error || !context ? <ErrorState /> : <PredictionRows data={context.predictions} />}</section>;
}
function RiskCard({ risk }: { risk: PredictionContext["risk"] }) { return <section className={`risk-card risk-${risk.level.toLowerCase()}`}><div><p className="eyebrow">RACE-OUTCOME RISK</p><h3>{risk.level} uncertainty</h3></div><ul>{risk.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></section>; }
function RaceReview({ context, loading, error, refresh }: { context: ReviewContext | null; loading: boolean; error: boolean; refresh: (fresh?: boolean) => Promise<void> }) { const [snapshot, setSnapshot] = useState<StoredSnapshot | null>(null); useEffect(() => { if (!context) return; try { const stored = window.localStorage.getItem(snapshotKey(context.race.round)); setSnapshot(stored ? JSON.parse(stored) as StoredSnapshot : null); } catch { setSnapshot(null); } }, [context]); if (loading) return <Loader />; if (error || !context) return <ErrorState />; if (!context.completed || !context.actualWinner) return <section className="glass prediction-card"><h2>Race review pending</h2><p className="data-note">The official classified result is not available yet.</p></section>; const predictedRank = snapshot?.predictions.findIndex((prediction) => prediction.driver === context.actualWinner?.driver) ?? -1; const predicted = predictedRank >= 0 ? snapshot?.predictions[predictedRank] : undefined; return <section className="glass prediction-card"><div className="table-head"><div><p className="eyebrow">POST-RACE REVIEW</p><h2>{context.race.name}</h2></div><button className="refresh" onClick={() => void refresh(true)}>Refresh result</button></div><div className="review-grid"><div><span>Actual winner</span><b>{context.actualWinner.driver}</b><small>{context.actualWinner.team}</small></div><div><span>Saved forecast</span><b>{snapshot ? stageLabel(snapshot.stage) : "No local snapshot"}</b><small>{snapshot ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(snapshot.savedAt)) : "Open Race Predictions before the race to capture it."}</small></div><div><span>Winner prediction</span><b>{predicted ? `#${predictedRank + 1} / ${predicted.winProbability}%` : "Not captured"}</b><small>{predicted ? "Compare this with the risk notes shown before the race." : "Future forecasts are stored automatically in this browser."}</small></div></div><p className="disclaimer">A different winner is reviewed as an outcome, not silently treated as a model failure. Strategy, Safety Cars, weather, damage and penalties remain race-execution variables; saved forecasts make that difference auditable.</p></section>; }
function PredictionRows({ data }: { data: Prediction[] }) { return <>{data.slice(0, 5).map((prediction, index) => <div className="prediction" key={prediction.driver}><strong>0{index + 1}</strong><div><b>{prediction.driver}</b><span>{prediction.team} / {prediction.confidence} confidence</span></div><div className="prob"><i style={{ width: `${prediction.winProbability}%` }} /><b>{prediction.winProbability}%</b></div><em>FORM {prediction.form}</em></div>)}</>; }
